#!/usr/bin/env bash
sbt_project() {
  project_folder=$1

  #create source folders
  mkdir -p ${project_folder}/src/{main,test}/{java,resources,scala}
  mkdir -p ${project_folder}/{lib,project,target}

  #create simple sbt config file 
  cat << EOF > ${project_folder}/build.sbt
name := baseDirectory.value.getName
version := "1.0-SNAPSHOT"
scalaVersion := "2.11.2"

val scalazVersion = "7.1.0"

libraryDependencies ++= Seq(
)

scalacOptions += "-feature"

initialCommands in console := ""
EOF

  cat << EOF > ${project_folder}/project/plugins.sbt
//resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
//addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.7.0-SNAPSHOT")
EOF
}
